# Generated by Django 4.2.2 on 2023-06-29 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 15, 37, 23, 714823, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guestcart',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 15, 37, 23, 714823, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='login_register',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2023, 6, 29, 15, 37, 23, 713781, tzinfo=datetime.timezone.utc)),
        ),
    ]
