# Generated by Django 4.2.2 on 2023-07-02 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_add_to_cart_create_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepie',
            new_name='News',
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 17, 22, 56, 724536, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guestcart',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 17, 22, 56, 724536, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='login_register',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 17, 22, 56, 723535, tzinfo=datetime.timezone.utc)),
        ),
    ]
