# Generated by Django 4.2.2 on 2023-07-02 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_recepie_news_alter_add_to_cart_create_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 21, 17, 45, 600557, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='guestcart',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 21, 17, 45, 601557, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='login_register',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 21, 17, 45, 600557, tzinfo=datetime.timezone.utc)),
        ),
    ]
